spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:rabbitdb
    username: user
    password: password
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2